plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = "funchole-backend"

include("certificate", "core", "controlplane", "gateway", "invocation", "invocation-contract", "dispatcher", "artifact", "runtime", "runtime-registry", "sandbox-protocol", "sandbox-manager")
